In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.3'

In [4]:
df = pd.read_excel(r'C:\Users\Nikhil\NVS Code\Pandas\01_first_code\data.xlsx')
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [5]:
df_cat = df[['CountryName','CountryCode','IncomeGroup']]
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [6]:
df_num = df[['BirthRate','InternetUsers']]

In [7]:
type(df)

pandas.DataFrame

In [8]:
len(df)

195

In [9]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='str')

In [10]:
df.shape

(195, 5)

In [11]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [12]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [13]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [14]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    str
 1   CountryCode    195 non-null    str
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    str
dtypes: float64(2), str(3)
memory usage: 12.9 KB

In [16]:
df_cat = df[['CountryName','CountryCode','IncomeGroup']]
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [17]:
df_num = df[['BirthRate','InternetUsers']]
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]